# Generated by Django 3.2.9 on 2021-11-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='conta',
            field=models.CharField(max_length=6, verbose_name=883150),
        ),
    ]
