# Generated by Django 3.2.9 on 2021-12-01 00:11

import conta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_auto_20211130_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='conta',
            field=models.CharField(default=conta.models.conta_random, max_length=6, serialize=False),
        ),
    ]
