# Generated by Django 3.2.9 on 2021-11-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=11)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.conta')),
            ],
        ),
    ]
