# Generated by Django 3.2.9 on 2021-11-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('conta', '0002_alter_conta_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorecido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conta.conta')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
        ),
    ]
