# Generated by Django 3.2.9 on 2021-12-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_alter_conta_conta'),
        ('transferencia', '0003_transferencia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='favorecido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conta_favorecido', to='conta.conta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conta_remetente', to='conta.conta'),
        ),
    ]
